service:
  name: ignite-todos

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws


functions: 
  listsTodos:
    handler: src/functions/listTodos.handle
    events:
      - http:
          path: /todos/{id}
          method: GET
          cors: true
    